name: Windows_With_EGL

on:
  workflow_dispatch:

concurrency:
  # cancel jobs on PRs only
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CCACHE_CONFIGPATH: C:/Users/runneradmin/AppData/Roaming/ccache/ccache.conf

jobs:
  build:
    name: Build MapLibre for Windows
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - arch: msvc2022_64
            compiler: x64

    steps:
      - name: git configure long path
        run: git config --global core.longpaths true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: hxbb00/maplibre-native
          submodules: recursive
          path: maplibre-native

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.compiler }}

      - name: Update ccache
        run: |
          choco upgrade ccache
          ccache --version

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: Windows_MapLibre_${{ matrix.arch }}
          max-size: 200M

      - name: Build MapLibre
        shell: bash
        env:
          COMPILER_TYPE: ${{ matrix.compiler }}
        run: |
          mkdir build && cd build
          cmake.exe ../maplibre-native/ \
            -G"Ninja Multi-Config" \
            -DCMAKE_CONFIGURATION_TYPES="Release;Debug" \
            -DCMAKE_C_COMPILER_LAUNCHER="ccache.exe" \
            -DCMAKE_CXX_COMPILER_LAUNCHER="ccache.exe" \
            -DMLN_WITH_EGL=ON \
            -DCMAKE_INSTALL_PREFIX="../install"
          ninja.exe

      - name: Upload sdk
        uses: actions/upload-artifact@v4
        with:
          name: MapLibre_Windows_${{ matrix.arch }}
          path: |
            build/**/*.lib
            build/CMakeFiles/**/*.pdb
            maplibre-native/include/
            maplibre-native/platform/windows/vendor/vcpkg/installed/x64-windows/
            maplibre-native/vendor/**/include/
